export const INCREMENT_COUNTER = 'App/INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'App/DECREMENT_COUNTER';

export const LOGIN_USER_PENDING = 'App/LOGIN_USER_PENDING';
export const LOGIN_USER_SUCCESS = 'App/LOGIN_USER_SUCCESS';
export const LOGIN_USER_ERROR = 'App/LOGIN_USER_ERROR';

export const LOGOUT_USER = 'App/LOGOUT_USER';
export const FORM_RESET = 'redux-form/RESET';

export const SCANNER_LOAD_INFO_PENDING = 'App/Scanner/LOAD_CLIENT_INFO_PENDING';
export const SCANNER_LOAD_INFO_SUCCESS = 'App/Scanner/SCANNER_LOAD_INFO_SUCCESS';
export const SCANNER_LOAD_INFO_ERROR = 'App/Scanner/SCANNER_LOAD_INFO_ERROR';

export const SCANNER_PRINT_CLIENT = 'App/Scanner/PRINT_CLIENT_INFO';


